# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

# monitor=,addreserved, 0, 0, 0, 0 # Custom reserved area


monitor=,preferred,auto,auto
monitor=HDMI-A-1,3440x1440@165,0x0,1.25
monitor=eDP-1,2880x1800@120,760x1440,1.5
# monitor=eDP-1,1920x1200@120,760x1440,1

# xwayland {
#   force_zero_scaling = true
# }

input {
    kb_layout = fr,us
    kb_variant = ,intl
    kb_options = grp:win_space_toggle, caps:swapescape
    kb_model =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = true
	scroll_factor = 0.4
    }
}

# HDMI port: mirror display. To see device name, use `hyprctl monitors`
